use quotopia;

-- Assuming author_id and genre_id are integer fields

-- Replace 'AuthorName' and 'GenreName' with the actual names in your database

INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('The future belongs to those who believe in the beauty of their dreams.', 7, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('The only impossible journey is the one you never begin.', 8, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Do not wait to strike till the iron is hot, but make it hot by striking.', 9, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Success is not final, failure is not fatal: It is the courage to continue that counts.', 10, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('The only source of knowledge is experience.', 11, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('I have not failed. I''ve just found 10,000 ways that won''t work.', 12, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Believe you can and you''re halfway there.', 13, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('The best way to predict the future is to create it.', 14, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('It always seems impossible until it''s done.', 15, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Don''t watch the clock; do what it does. Keep going.', 16, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Life is what happens when you''re busy making other plans.', 17, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Whatever you are, be a good one.', 18, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Strive not to be a success, but rather to be of value.', 19, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('It''s not whether you get knocked down, it''s whether you get up.', 20, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('The only way to do great work is to love what you do.', 21, 1);

INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Success usually comes to those who are too busy to be looking for it.', 22, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('You miss 100% of the shots you don''t take.', 23, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('I attribute my success to this: I never gave or took any excuse.', 24, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Don''t cry because it''s over, smile because it happened.', 25, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('The purpose of our lives is to be happy.', 26, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Life is what happens when you''re busy making other plans.', 27, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('You have within you right now, everything you need to deal with whatever the world can throw at you.', 28, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Success is not final, failure is not fatal: It is the courage to continue that counts.', 29, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('The only limit to our realization of tomorrow will be our doubts of today.', 30, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('The greatest glory in living lies not in never falling, but in rising every time we fall.', 31, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('The only thing we have to fear is fear itself.', 32, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('In three words I can sum up everything I''ve learned about life: it goes on.', 33, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.', 34, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('The only way to do great work is to love what you do.', 35, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('The future belongs to those who believe in the beauty of their dreams.', 36, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('The only impossible journey is the one you never begin.', 37, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Do not wait to strike till the iron is hot, but make it hot by striking.', 38, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Success is not final, failure is not fatal: It is the courage to continue that counts.', 39, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('The only source of knowledge is experience.', 40, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('I have not failed. I''ve just found 10,000 ways that won''t work.', 41, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Believe you can and you''re halfway there.', 42, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('The best way to predict the future is to create it.', 43, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('It always seems impossible until it''s done.', 44, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Don''t watch the clock; do what it does. Keep going.', 45, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Life is what happens when you''re busy making other plans.', 46, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Whatever you are, be a good one.', 47, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Strive not to be a success, but rather to be of value.', 48, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('It''s not whether you get knocked down, it''s whether you get up.', 49, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('The only way to do great work is to love what you do.', 50, 1);

INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Success usually comes to those who are too busy to be looking for it.', 51, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('You miss 100% of the shots you don''t take.', 52, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('I attribute my success to this: I never gave or took any excuse.', 53, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Don''t cry because it''s over, smile because it happened.', 54, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('The purpose of our lives is to be happy.', 55, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Life is what happens when you''re busy making other plans.', 56, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('You have within you right now, everything you need to deal with whatever the world can throw at you.', 57, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Success is not final, failure is not fatal: It is the courage to continue that counts.', 58, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('The only limit to our realization of tomorrow will be our doubts of today.', 59, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('The greatest glory in living lies not in never falling, but in rising every time we fall.', 60, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('The only thing we have to fear is fear itself.', 61, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('In three words I can sum up everything I''ve learned about life: it goes on.', 62, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.', 63, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('The only way to do great work is to love what you do.', 64, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('The future belongs to those who believe in the beauty of their dreams.', 65, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('The only impossible journey is the one you never begin.', 66, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Do not wait to strike till the iron is hot, but make it hot by striking.', 67, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Success is not final, failure is not fatal: It is the courage to continue that counts.', 68, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('The only source of knowledge is experience.', 69, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('I have not failed. I''ve just found 10,000 ways that won''t work.', 70, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Believe you can and you''re halfway there.', 71, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('The best way to predict the future is to create it.', 72, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('It always seems impossible until it''s done.', 73, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Don''t watch the clock; do what it does. Keep going.', 74, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Life is what happens when you''re busy making other plans.', 75, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Whatever you are, be a good one.', 76, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Strive not to be a success, but rather to be of value.', 77, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('It''s not whether you get knocked down, it''s whether you get up.', 78, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('The only way to do great work is to love what you do.', 79, 1);

INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Success usually comes to those who are too busy to be looking for it.', 80, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('You miss 100% of the shots you don''t take.', 81, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('I attribute my success to this: I never gave or took any excuse.', 82, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Don''t cry because it''s over, smile because it happened.', 83, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('The purpose of our lives is to be happy.', 84, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Life is what happens when you''re busy making other plans.', 85, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('You have within you right now, everything you need to deal with whatever the world can throw at you.', 86, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Success is not final, failure is not fatal: It is the courage to continue that counts.', 87, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('The only limit to our realization of tomorrow will be our doubts of today.', 88, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('The greatest glory in living lies not in never falling, but in rising every time we fall.', 89, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('The only thing we have to fear is fear itself.', 90, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('In three words I can sum up everything I''ve learned about life: it goes on.', 91, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.', 92, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('The only way to do great work is to love what you do.', 93, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('The future belongs to those who believe in the beauty of their dreams.', 94, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('The only impossible journey is the one you never begin.', 95, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Do not wait to strike till the iron is hot, but make it hot by striking.', 96, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Success is not final, failure is not fatal: It is the courage to continue that counts.', 97, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('The only source of knowledge is experience.', 98, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('I have not failed. I''ve just found 10,000 ways that won''t work.', 99, 1);
INSERT INTO quotes (quote_text, author_id, genre_id) VALUES ('Believe you can and you''re halfway there.', 100, 1);
